name: push
on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install -g dockerlint
      - run: dockerlint
  build-push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: meta
        id: meta
        run: |
          version="$(grep apache-superset Pipfile | grep -Eo '[0-9.]+')"
          tags="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$version"
          echo "tags=$tags" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
